// dict-vi.js — Vietnamese phrase dictionary (200+ entries)
// Auto-generated for HowDoISay app
var DICT_VI = {
  // ===== GREETINGS & COURTESY (20) =====
  "hello": {t:"xin chào", s:[{t:"xin",m:"Sin",h:"the word 'sin'"},{t:"chào",m:"Chow",h:"like 'chow' mein"}]},
  "good morning": {t:"chào buổi sáng", s:[{t:"chào",m:"Chow",h:"like 'chow' mein"},{t:"buổi",m:"Boy",h:"like 'buoy'"},{t:"sáng",m:"Sang",h:"the word 'sang'"}]},
  "good afternoon": {t:"chào buổi chiều", s:[{t:"chào",m:"Chow",h:"like 'chow' mein"},{t:"buổi",m:"Boy",h:"like 'buoy'"},{t:"chiều",m:"Chew",h:"the word 'chew'"}]},
  "good evening": {t:"chào buổi tối", s:[{t:"chào",m:"Chow",h:"like 'chow' mein"},{t:"buổi",m:"Boy",h:"like 'buoy'"},{t:"tối",m:"Toy",h:"the word 'toy'"}]},
  "good night": {t:"chúc ngủ ngon", s:[{t:"chúc",m:"Chook",h:"'chew' + 'K' at end"},{t:"ngủ",m:"Noo",h:"'noon' without last N, say NG at start"},{t:"ngon",m:"Non",h:"'non' but with NG at start like 'sing'"}]},
  "goodbye": {t:"tạm biệt", s:[{t:"tạm",m:"Tom",h:"the name 'Tom'"},{t:"biệt",m:"Bee-et",h:"'bee' + 'et'"}]},
  "thank you": {t:"cảm ơn", s:[{t:"cảm",m:"Calm",h:"the word 'calm'"},{t:"ơn",m:"Un",h:"'un-' like in 'undo'"}]},
  "thank you very much": {t:"cảm ơn rất nhiều", s:[{t:"cảm",m:"Calm",h:"the word 'calm'"},{t:"ơn",m:"Un",h:"'un-' like in 'undo'"},{t:"rất",m:"Rat",h:"the word 'rat'"},{t:"nhiều",m:"Noo",h:"'noon' without last N, say NG at start"}]},
  "you're welcome": {t:"không có chi", s:[{t:"không",m:"Kong",h:"like King Kong"},{t:"có",m:"Kaw",h:"like 'caw' of a crow"},{t:"chi",m:"Chee",h:"'chi' like Greek letter"}]},
  "excuse me": {t:"xin lỗi", s:[{t:"xin",m:"Sin",h:"the word 'sin'"},{t:"lỗi",m:"Loy",h:"'loy' like a word"}]},
  "i'm sorry": {t:"tôi xin lỗi", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"xin",m:"Sin",h:"the word 'sin'"},{t:"lỗi",m:"Loy",h:"'loy' like a word"}]},
  "please": {t:"vui lòng", s:[{t:"vui",m:"Voo",h:"'voo' like in voodoo"},{t:"lòng",m:"Long",h:"the word 'long'"}]},
  "nice to meet you": {t:"rất vui được gặp bạn", s:[{t:"rất",m:"Rat",h:"the word 'rat'"},{t:"vui",m:"Voo",h:"'voo' like in voodoo"},{t:"được",m:"Duke",h:"the name 'Duke'"},{t:"gặp",m:"Gap",h:"the word 'gap'"},{t:"bạn",m:"Ban",h:"the word 'ban'"}]},
  "how are you": {t:"bạn khỏe không", s:[{t:"bạn",m:"Ban",h:"the word 'ban'"},{t:"khỏe",m:"Kweh",h:"'K' then 'way'"},{t:"không",m:"Kong",h:"like King Kong"}]},
  "i'm fine": {t:"tôi khỏe", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"khỏe",m:"Kweh",h:"'K' then 'way'"}]},
  "what is your name": {t:"tên bạn là gì", s:[{t:"tên",m:"Ten",h:"the number 'ten'"},{t:"bạn",m:"Ban",h:"the word 'ban'"},{t:"là",m:"Lah",h:"'la' like a musical note"},{t:"gì",m:"Zee",h:"the letter 'Z'"}]},
  "my name is": {t:"tên tôi là", s:[{t:"tên",m:"Ten",h:"the number 'ten'"},{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"là",m:"Lah",h:"'la' like a musical note"}]},
  "pleased to meet you": {t:"được biết bạn là điều vui", s:[{t:"được",m:"Duke",h:"the name 'Duke'"},{t:"biết",m:"Bee-et",h:"'bee' + 'et'"},{t:"bạn",m:"Ban",h:"the word 'ban'"},{t:"là",m:"Lah",h:"'la' like a musical note"},{t:"điều",m:"Dee-oo",h:"letter 'D' + 'oo'"},{t:"vui",m:"Voo",h:"'voo' like in voodoo"}]},
  "congratulations": {t:"xin chúc mừng", s:[{t:"xin",m:"Sin",h:"the word 'sin'"},{t:"chúc",m:"Chook",h:"'chew' + 'K' at end"},{t:"mừng",m:"Mung",h:"'mung' bean"}]},
  "happy birthday": {t:"sinh nhật vui vẻ", s:[{t:"sinh",m:"Sin",h:"the word 'sin'"},{t:"nhật",m:"Nyat",h:"'N' then 'yacht'"},{t:"vui",m:"Voo",h:"'voo' like in voodoo"},{t:"vẻ",m:"Veh",h:"'veh' like 'vat'"}]},

  // ===== YES/NO/BASICS (10) =====
  "yes": {t:"vâng", s:[{t:"vâng",m:"Vung",h:"'vuh' + 'ng' like in 'sing'"}]},
  "no": {t:"không", s:[{t:"không",m:"Kong",h:"like King Kong"}]},
  "ok": {t:"được", s:[{t:"được",m:"Duke",h:"the name 'Duke'"}]},
  "i understand": {t:"tôi hiểu rồi", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"hiểu",m:"Hoo",h:"'hoo' like an owl"},{t:"rồi",m:"Roy",h:"the name 'Roy'"}]},
  "i don't understand": {t:"tôi không hiểu", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"không",m:"Kong",h:"like King Kong"},{t:"hiểu",m:"Hoo",h:"'hoo' like an owl"}]},
  "do you speak english": {t:"bạn có nói tiếng anh không", s:[{t:"bạn",m:"Ban",h:"the word 'ban'"},{t:"có",m:"Kaw",h:"like 'caw' of a crow"},{t:"nói",m:"Noy",h:"'noy' like a word"},{t:"tiếng",m:"Tee-ung",h:"'tea' + 'ung'"},{t:"anh",m:"Anh",h:"like the name 'Ann'"},{t:"không",m:"Kong",h:"like King Kong"}]},
  "slowly please": {t:"nói chậm lại được không", s:[{t:"nói",m:"Noy",h:"'noy' like a word"},{t:"chậm",m:"Chum",h:"'chum' like buddy"},{t:"lại",m:"Lie",h:"the word 'lie'"},{t:"được",m:"Duke",h:"the name 'Duke'"},{t:"không",m:"Kong",h:"like King Kong"}]},
  "can you help me": {t:"bạn có thể giúp tôi không", s:[{t:"bạn",m:"Ban",h:"the word 'ban'"},{t:"có",m:"Kaw",h:"like 'caw' of a crow"},{t:"thể",m:"Thuh",h:"'the' with uh"},{t:"giúp",m:"Yoop",h:"'yoop' like to whoop"},{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"không",m:"Kong",h:"like King Kong"}]},
  "where is": {t:"cái gì ở đâu", s:[{t:"cái",m:"Kai",h:"like 'kai' Hawaiian word"},{t:"gì",m:"Zee",h:"the letter 'Z'"},{t:"ở",m:"Uh",h:"'uh' like 'huh'"},{t:"đâu",m:"Duh",h:"'duh' like 'duh' sound"}]},
  "how much": {t:"bao nhiêu tiền", s:[{t:"bao",m:"Bow",h:"like 'bow' and arrow"},{t:"nhiêu",m:"Noo",h:"'noon' without last N"},{t:"tiền",m:"Tee-in",h:"'teen' but with 'in'"}]},

  // ===== EMERGENCY & SAFETY (15) =====
  "help": {t:"cứu tôi", s:[{t:"cứu",m:"Soo",h:"the word 'Sue'"},{t:"tôi",m:"Toy",h:"the word 'toy'"}]},
  "emergency": {t:"khẩn cấp", s:[{t:"khẩn",m:"Khan",h:"like Khan from Star Trek"},{t:"cấp",m:"Kahp",h:"'cap' with ah"}]},
  "call the police": {t:"gọi cảnh sát", s:[{t:"gọi",m:"Goy",h:"'goy' like a word"},{t:"cảnh",m:"Kahnh",h:"'calm' + 'h'"},{t:"sát",m:"Saht",h:"'sat' with h at end"}]},
  "call the doctor": {t:"gọi bác sĩ", s:[{t:"gọi",m:"Goy",h:"'goy' like a word"},{t:"bác",m:"Bahk",h:"'back' without ck"},{t:"sĩ",m:"See",h:"the word 'see'"}]},
  "hospital": {t:"bệnh viện", s:[{t:"bệnh",m:"Ben",h:"the name 'Ben'"},{t:"viện",m:"Vyen",h:"'vee' + 'en'"}]},
  "fire": {t:"lửa", s:[{t:"lửa",m:"Loo-uh",h:"'loom' without m + 'uh'"}]},
  "danger": {t:"nguy hiểm", s:[{t:"nguy",m:"Nwee",h:"NG sound + 'we'"},{t:"hiểm",m:"Hum",h:"like 'hum' sound"}]},
  "watch out": {t:"cẩn thận", s:[{t:"cẩn",m:"Kun",h:"like 'can' but with uh"},{t:"thận",m:"Than",h:"'than' like 'than' in comparison"}]},
  "i'm lost": {t:"tôi bị lạc", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"bị",m:"Bee",h:"the word 'bee'"},{t:"lạc",m:"Lahk",h:"'lock' without ck"}]},
  "i'm sick": {t:"tôi bị ốm", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"bị",m:"Bee",h:"the word 'bee'"},{t:"ốm",m:"Um",h:"the word 'um'"}]},
  "call an ambulance": {t:"gọi xe cấp cứu", s:[{t:"gọi",m:"Goy",h:"'goy' like a word"},{t:"xe",m:"Seh",h:"'say' without y"},{t:"cấp",m:"Kahp",h:"'cap' with ah"},{t:"cứu",m:"Soo",h:"the word 'Sue'"}]},
  "i need a doctor": {t:"tôi cần bác sĩ", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"cần",m:"Kun",h:"like 'can' but with uh"},{t:"bác",m:"Bahk",h:"'back' without ck"},{t:"sĩ",m:"See",h:"the word 'see'"}]},
  "passport": {t:"hộ chiếu", s:[{t:"hộ",m:"Huh",h:"the word 'huh'"},{t:"chiếu",m:"Chew",h:"the word 'chew'"}]},
  "visa": {t:"thị thực", s:[{t:"thị",m:"Thee",h:"the letter 'T' said 'thee'"},{t:"thực",m:"Thook",h:"'took' with th"}]},
  "police station": {t:"đồn cảnh sát", s:[{t:"đồn",m:"Dun",h:"'done' without e"},{t:"cảnh",m:"Kahnh",h:"'calm' + 'h'"},{t:"sát",m:"Saht",h:"'sat' with h at end"}]},

  // ===== NUMBERS 0-10, 20, 50, 100, 1000 (15) =====
  "zero": {t:"không", s:[{t:"không",m:"Kong",h:"like King Kong"}]},
  "one": {t:"một", s:[{t:"một",m:"Mot",h:"'mot' like motorcycle"}]},
  "two": {t:"hai", s:[{t:"hai",m:"Hi",h:"the word 'hi'"}]},
  "three": {t:"ba", s:[{t:"ba",m:"Bah",h:"the word 'bah'"}]},
  "four": {t:"bốn", s:[{t:"bốn",m:"Bawn",h:"'born' without r"}]},
  "five": {t:"năm", s:[{t:"năm",m:"Num",h:"'nom' like nom nom"}]},
  "six": {t:"sáu", s:[{t:"sáu",m:"Sow",h:"like 'sew' or 'sow'"}]},
  "seven": {t:"bảy", s:[{t:"bảy",m:"By",h:"the word 'by'"}]},
  "eight": {t:"tám", s:[{t:"tám",m:"Tom",h:"the name 'Tom'"}]},
  "nine": {t:"chín", s:[{t:"chín",m:"Chin",h:"the word 'chin'"}]},
  "ten": {t:"mười", s:[{t:"mười",m:"Moo-uh",h:"'moo' of cow + 'uh'"}]},
  "twenty": {t:"hai mươi", s:[{t:"hai",m:"Hi",h:"the word 'hi'"},{t:"mươi",m:"Moo-uh",h:"'moo' of cow + 'uh'"}]},
  "fifty": {t:"năm mươi", s:[{t:"năm",m:"Num",h:"'nom' like nom nom"},{t:"mươi",m:"Moo-uh",h:"'moo' of cow + 'uh'"}]},
  "one hundred": {t:"một trăm", s:[{t:"một",m:"Mot",h:"'mot' like motorcycle"},{t:"trăm",m:"Chum",h:"'chum' like buddy"}]},
  "one thousand": {t:"một nghìn", s:[{t:"một",m:"Mot",h:"'mot' like motorcycle"},{t:"nghìn",m:"Ngin",h:"NG sound + 'in'"}]},

  // ===== FOOD & DRINK (30) =====
  "water": {t:"nước", s:[{t:"nước",m:"Nook",h:"'nook' and cranny"}]},
  "coffee": {t:"cà phê", s:[{t:"cà",m:"Kah",h:"'ka' like in karate"},{t:"phê",m:"Fay",h:"'fay' like a fairy"}]},
  "tea": {t:"trà", s:[{t:"trà",m:"Chah",h:"'cha' like tea in some languages"}]},
  "beer": {t:"bia", s:[{t:"bia",m:"Bee-ah",h:"'bee' + 'ah'"}]},
  "wine": {t:"rượu vang", s:[{t:"rượu",m:"Zoo-uh",h:"'zoo' + 'uh'"},{t:"vang",m:"Vang",h:"'vang' like a word"}]},
  "rice": {t:"cơm", s:[{t:"cơm",m:"Cum",h:"'cum' like in cum laude"}]},
  "noodles": {t:"mì", s:[{t:"mì",m:"Mee",h:"the word 'me'"}]},
  "pho": {t:"phở", s:[{t:"phở",m:"Fuh",h:"'fun' without the N"}]},
  "chicken": {t:"gà", s:[{t:"gà",m:"Gah",h:"'got' without the T"}]},
  "pork": {t:"lợn", s:[{t:"lợn",m:"Lun",h:"'lune' like lunar"}]},
  "beef": {t:"thịt bò", s:[{t:"thịt",m:"Tit",h:"'tat' sound"},{t:"bò",m:"Bow",h:"like 'bow' and arrow"}]},
  "fish": {t:"cá", s:[{t:"cá",m:"Kah",h:"'ka' like in karate"}]},
  "shrimp": {t:"tôm", s:[{t:"tôm",m:"Tom",h:"the name 'Tom'"}]},
  "egg": {t:"trứng", s:[{t:"trứng",m:"Chung",h:"like 'young' with ch"}]},
  "bread": {t:"bánh mì", s:[{t:"bánh",m:"Ban",h:"the word 'ban'"},{t:"mì",m:"Mee",h:"the word 'me'"}]},
  "vegetable": {t:"rau", s:[{t:"rau",m:"Zow",h:"like 'zoo' with 'ow'"}]},
  "fruit": {t:"quả", s:[{t:"quả",m:"Kwah",h:"'K' + 'wah'"}]},
  "apple": {t:"quả táo", s:[{t:"quả",m:"Kwah",h:"'K' + 'wah'"},{t:"táo",m:"Tow",h:"like 'toe'"}]},
  "banana": {t:"quả chuối", s:[{t:"quả",m:"Kwah",h:"'K' + 'wah'"},{t:"chuối",m:"Chway",h:"'chew' + 'ay'"}]},
  "mango": {t:"quả xoài", s:[{t:"quả",m:"Kwah",h:"'K' + 'wah'"},{t:"xoài",m:"Swye",h:"'S' + 'way'"}]},
  "orange": {t:"quả cam", s:[{t:"quả",m:"Kwah",h:"'K' + 'wah'"},{t:"cam",m:"Kahm",h:"'calm' without L"}]},
  "soup": {t:"canh", s:[{t:"canh",m:"Kahnh",h:"'calm' + 'h'"}]},
  "dessert": {t:"tráng miệng", s:[{t:"tráng",m:"Chang",h:"'chung' sound"},{t:"miệng",m:"Myung",h:"'M' + 'young'"}]},
  "salt": {t:"muối", s:[{t:"muối",m:"Moo-ee",h:"'moo' + 'ee'"}]},
  "sugar": {t:"đường", s:[{t:"đường",m:"Doo-ung",h:"'doo' + 'ung'"}]},
  "spicy": {t:"cay", s:[{t:"cay",m:"Kai",h:"like 'kai' Hawaiian word"}]},
  "delicious": {t:"ngon", s:[{t:"ngon",m:"Non",h:"'non' but with NG at start like 'sing'"}]},
  "milk": {t:"sữa", s:[{t:"sữa",m:"Soo-uh",h:"'sue' + 'uh'"}]},
  "juice": {t:"nước ép", s:[{t:"nước",m:"Nook",h:"'nook' and cranny"},{t:"ép",m:"Up",h:"the word 'up'"}]},
  "soft drink": {t:"nước ngọt", s:[{t:"nước",m:"Nook",h:"'nook' and cranny"},{t:"ngọt",m:"Ngot",h:"NG sound + 'aught'"}]},

  // ===== RESTAURANT (15) =====
  "restaurant": {t:"nhà hàng", s:[{t:"nhà",m:"Nyah",h:"'N' then 'yah'"},{t:"hàng",m:"Hang",h:"the word 'hang'"}]},
  "table": {t:"bàn", s:[{t:"bàn",m:"Ban",h:"the word 'ban'"}]},
  "menu": {t:"thực đơn", s:[{t:"thực",m:"Thook",h:"'took' with th"},{t:"đơn",m:"Dun",h:"'done' without e"}]},
  "waiter": {t:"bồi bàn", s:[{t:"bồi",m:"Boy",h:"the word 'boy'"},{t:"bàn",m:"Ban",h:"the word 'ban'"}]},
  "check": {t:"hóa đơn", s:[{t:"hóa",m:"Hwah",h:"'H' + 'wah'"},{t:"đơn",m:"Dun",h:"'done' without e"}]},
  "i would like": {t:"tôi muốn", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"muốn",m:"Mwan",h:"'moon' without n + 'aw'"}]},
  "the bill please": {t:"tính tiền", s:[{t:"tính",m:"Ting",h:"the word 'ting'"},{t:"tiền",m:"Tee-in",h:"'teen' but with 'in'"}]},
  "the same": {t:"giống như thế", s:[{t:"giống",m:"Yawng",h:"'young' + 'ng' sound"},{t:"như",m:"Noo",h:"'noon' without last N"},{t:"thế",m:"Theh",h:"'the' + 'uh'"}]},
  "no ice": {t:"không đá", s:[{t:"không",m:"Kong",h:"like King Kong"},{t:"đá",m:"Dah",h:"like 'dah' (da da da)"}]},
  "very hot": {t:"rất nóng", s:[{t:"rất",m:"Rat",h:"the word 'rat'"},{t:"nóng",m:"Nong",h:"'n' + 'ong' like song"}]},
  "cold": {t:"lạnh", s:[{t:"lạnh",m:"Lahn",h:"'lahn' like 'land' without d"}]},
  "hot": {t:"nóng", s:[{t:"nóng",m:"Nong",h:"'n' + 'ong' like song"}]},
  "sweet": {t:"ngọt", s:[{t:"ngọt",m:"Ngot",h:"NG sound + 'aught'"}]},
  "salty": {t:"mặn", s:[{t:"mặn",m:"Mun",h:"like 'man' but with u"}]},
  "sour": {t:"chua", s:[{t:"chua",m:"Choo-uh",h:"'chew' + 'uh'"}]},

  // ===== SHOPPING & MONEY (20) =====
  "shop": {t:"cửa hàng", s:[{t:"cửa",m:"Koo-uh",h:"'coo' + 'uh'"},{t:"hàng",m:"Hang",h:"the word 'hang'"}]},
  "market": {t:"chợ", s:[{t:"chợ",m:"Chaw",h:"'chaw' like chewing"}]},
  "money": {t:"tiền", s:[{t:"tiền",m:"Tee-in",h:"'teen' but with 'in'"}]},
  "how much cost": {t:"giá bao nhiêu", s:[{t:"giá",m:"Yah",h:"'yeah' without h"},{t:"bao",m:"Bow",h:"like 'bow' and arrow"},{t:"nhiêu",m:"Noo",h:"'noon' without last N"}]},
  "expensive": {t:"đắt", s:[{t:"đắt",m:"Daht",h:"'dot' with ah"}]},
  "cheap": {t:"rẻ", s:[{t:"rẻ",m:"Zeh",h:"'zay' like a word"}]},
  "discount": {t:"giảm giá", s:[{t:"giảm",m:"Yahm",h:"'yam' the vegetable"},{t:"giá",m:"Yah",h:"'yeah' without h"}]},
  "credit card": {t:"thẻ tín dụng", s:[{t:"thẻ",m:"Theh",h:"'the' + 'uh'"},{t:"tín",m:"Tin",h:"the word 'tin'"},{t:"dụng",m:"Yoong",h:"'young' without y"}]},
  "cash": {t:"tiền mặt", s:[{t:"tiền",m:"Tee-in",h:"'teen' but with 'in'"},{t:"mặt",m:"Maht",h:"'mat' with ah"}]},
  "i'll take it": {t:"tôi lấy cái này", s:[{t:"tôi",m:"Toy",h:"the word 'toy'"},{t:"lấy",m:"Lay",h:"the word 'lay'"},{t:"cái",m:"Kai",h:"like 'kai' Hawaiian word"},{t:"này",m:"Nay",h:"the word 'nay'"}]},
  "too expensive": {t:"đắt quá", s:[{t:"đắt",m:"Daht",h:"'dot' with ah"},{t:"quá",m:"Kwah",h:"'K' + 'wah'"}]},
  "do you have": {t:"bạn có", s:[{t:"bạn",m:"Ban",h:"the word 'ban'"},{t:"có",m:"Kaw",h:"like 'caw' of a crow"}]},
  "what size": {t:"kích thước bao nhiêu", s:[{t:"kích",m:"Kick",h:"the word 'kick'"},{t:"thước",m:"Thook",h:"'took' with th"},{t:"bao",m:"Bow",h:"like 'bow' and arrow"},{t:"nhiêu",m:"Noo",h:"'noon' without last N"}]},
  "what color": {t:"màu gì", s:[{t:"màu",m:"Mow",h:"like 'mow' the lawn"},{t:"gì",m:"Zee",h:"the letter 'Z'"}]},
  "red": {t:"đỏ", s:[{t:"đỏ",m:"Daw",h:"like 'daw' sound"}]},
  "blue": {t:"xanh", s:[{t:"xanh",m:"San",h:"the name 'San'"}]},
  "white": {t:"trắng", s:[{t:"trắng",m:"Chang",h:"like 'young' with ch"}]},
  "black": {t:"đen", s:[{t:"đen",m:"Den",h:"the name 'Den'"}]},
  "yellow": {t:"vàng", s:[{t:"vàng",m:"Vang",h:"'vang' like a word"}]},

  // ===== DIRECTIONS & TRANSPORTATION (25) =====
  "taxi": {t:"xe taxi", s:[{t:"xe",m:"Seh",h:"'say' without y"},{t:"taxi",m:"Tack-see",h:"the word 'taxi'"}]},
  "bus": {t:"xe buýt", s:[{t:"xe",m:"Seh",h:"'say' without y"},{t:"buýt",m:"Bwit",h:"'bwit' like a word"}]},
  "train": {t:"tàu hỏa", s:[{t:"tàu",m:"Tow",h:"like 'toe'"},{t:"hỏa",m:"Hwah",h:"'H' + 'wah'"}]},
  "airplane": {t:"máy bay", s:[{t:"máy",m:"May",h:"the month 'May'"},{t:"bay",m:"By",h:"the word 'by'"}]},
  "bike": {t:"xe đạp", s:[{t:"xe",m:"Seh",h:"'say' without y"},{t:"đạp",m:"Dahp",h:"'dap' with ah"}]},
  "motorbike": {t:"xe máy", s:[{t:"xe",m:"Seh",h:"'say' without y"},{t:"máy",m:"May",h:"the month 'May'"}]},
  "car": {t:"ô tô", s:[{t:"ô",m:"Oh",h:"the word 'oh'"},{t:"tô",m:"Toh",h:"'toe' + 'uh'"}]},
  "street": {t:"đường phố", s:[{t:"đường",m:"Doo-ung",h:"'doo' + 'ung'"},{t:"phố",m:"Faw",h:"like 'faw' sound"}]},
  "turn left": {t:"quay trái", s:[{t:"quay",m:"Kway",h:"'K' + 'way'"},{t:"trái",m:"Chai",h:"'chai' like tea"}]},
  "turn right": {t:"quay phải", s:[{t:"quay",m:"Kway",h:"'K' + 'way'"},{t:"phải",m:"Fye",h:"'fye' like 'fiance'"}]},
  "go straight": {t:"đi thẳng", s:[{t:"đi",m:"Dee",h:"the letter 'D'"},{t:"thẳng",m:"Thung",h:"'thung' like 'thong'"}]},
  "north": {t:"hướng bắc", s:[{t:"hướng",m:"Hung",h:"'hung' like past tense"},{t:"bắc",m:"Bahk",h:"'back' without ck"}]},
  "south": {t:"hướng nam", s:[{t:"hướng",m:"Hung",h:"'hung' like past tense"},{t:"nam",m:"Nahm",h:"like 'nom' nom"}]},
  "east": {t:"hướng đông", s:[{t:"hướng",m:"Hung",h:"'hung' like past tense"},{t:"đông",m:"Dong",h:"the word 'dong'"}]},
  "west": {t:"hướng tây", s:[{t:"hướng",m:"Hung",h:"'hung' like past tense"},{t:"tây",m:"Tay",h:"like 'tie' or 'Thai'"}]},
  "near": {t:"gần", s:[{t:"gần",m:"Gun",h:"the word 'gun'"}]},
  "far": {t:"xa", s:[{t:"xa",m:"Sah",h:"'sa' like in salsa"}]},
  "stop": {t:"dừng", s:[{t:"dừng",m:"Dung",h:"'dung' like manure"}]},
  "faster": {t:"nhanh hơn", s:[{t:"nhanh",m:"Nahn",h:"'nan' like bread"},{t:"hơn",m:"Hun",h:"'hun' like honey"}]},
  "slower": {t:"chậm hơn", s:[{t:"chậm",m:"Chum",h:"'chum' like buddy"},{t:"hơn",m:"Hun",h:"'hun' like honey"}]},
  "station": {t:"ga", s:[{t:"ga",m:"Gah",h:"'got' without the T"}]},
  "ticket": {t:"vé", s:[{t:"vé",m:"Vay",h:"'vay' like a word"}]},
  "airport": {t:"sân bay", s:[{t:"sân",m:"Sun",h:"the word 'sun'"},{t:"bay",m:"By",h:"the word 'by'"}]},
  "bridge": {t:"cầu", s:[{t:"cầu",m:"Cow",h:"the animal 'cow'"}]},
  "road": {t:"con đường", s:[{t:"con",m:"Kun",h:"like 'con' game"},{t:"đường",m:"Doo-ung",h:"'doo' + 'ung'"}]},

  // ===== ACCOMMODATION (15) =====
  "hotel": {t:"khách sạn", s:[{t:"khách",m:"Khahk",h:"'khan' + 'ck'"},{t:"sạn",m:"San",h:"the name 'San'"}]},
  "room": {t:"phòng", s:[{t:"phòng",m:"Fong",h:"'fong' like gong"}]},
  "bed": {t:"giường", s:[{t:"giường",m:"Yoo-ung",h:"'young' without y"}]},
  "bathroom": {t:"phòng tắm", s:[{t:"phòng",m:"Fong",h:"'fong' like gong"},{t:"tắm",m:"Tum",h:"'tummy' without my"}]},
  "shower": {t:"vòi sen", s:[{t:"vòi",m:"Voy",h:"'voy' like a word"},{t:"sen",m:"Sen",h:"the name 'Sen'"}]},
  "pillow": {t:"gối", s:[{t:"gối",m:"Goy",h:"'goy' like a word"}]},
  "blanket": {t:"chăn", s:[{t:"chăn",m:"Chun",h:"'chun' like chunk"}]},
  "towel": {t:"khăn tắm", s:[{t:"khăn",m:"Khan",h:"like Khan from Star Trek"},{t:"tắm",m:"Tum",h:"'tummy' without my"}]},
  "key": {t:"chìa khóa", s:[{t:"chìa",m:"Chee-uh",h:"'chee' + 'uh'"},{t:"khóa",m:"Kwah",h:"'K' + 'wah'"}]},
  "check in": {t:"đăng ký nhập", s:[{t:"đăng",m:"Dahng",h:"'dang' like dang it"},{t:"ký",m:"Kee",h:"like 'key'"},{t:"nhập",m:"Nyup",h:"'N' + 'yup'"}]},
  "check out": {t:"trả phòng", s:[{t:"trả",m:"Chah",h:"'cha' like tea"},{t:"phòng",m:"Fong",h:"'fong' like gong"}]},
  "reservation": {t:"đặt phòng", s:[{t:"đặt",m:"Daht",h:"'dot' with ah"},{t:"phòng",m:"Fong",h:"'fong' like gong"}]},
  "wifi": {t:"wifi", s:[{t:"wifi",m:"Wee-fee",h:"the word 'wifi'"}]},
  "air conditioning": {t:"điều hòa", s:[{t:"điều",m:"Dee-oo",h:"letter 'D' + 'oo'"},{t:"hòa",m:"Hwah",h:"'H' + 'wah'"}]},
  "fan": {t:"quạt", s:[{t:"quạt",m:"Kwat",h:"'K' + 'what'"}]},

  // ===== COMMUNICATION (15) =====
  "phone": {t:"điện thoại", s:[{t:"điện",m:"Dyen",h:"letter 'D' + 'yen'"},{t:"thoại",m:"Thwai",h:"'th' + 'way'"}]},
  "mobile": {t:"điện thoại di động", s:[{t:"điện",m:"Dyen",h:"letter 'D' + 'yen'"},{t:"thoại",m:"Thwai",h:"'th' + 'way'"},{t:"di",m:"Zee",h:"the letter 'Z'"},{t:"động",m:"Dong",h:"the word 'dong'"}]},
  "internet": {t:"internet", s:[{t:"internet",m:"In-ter-net",h:"the word 'internet'"}]},
  "email": {t:"email", s:[{t:"email",m:"E-mail",h:"the word 'email'"}]},
  "telephone": {t:"điện thoại", s:[{t:"điện",m:"Dyen",h:"letter 'D' + 'yen'"},{t:"thoại",m:"Thwai",h:"'th' + 'way'"}]},
  "send message": {t:"gửi tin nhắn", s:[{t:"gửi",m:"Goo-uh",h:"'goo' + 'uh'"},{t:"tin",m:"Tin",h:"the word 'tin'"},{t:"nhắn",m:"Nahn",h:"'nan' like bread"}]},
  "call me": {t:"gọi tôi", s:[{t:"gọi",m:"Goy",h:"'goy' like a word"},{t:"tôi",m:"Toy",h:"the word 'toy'"}]},
  "text message": {t:"tin nhắn", s:[{t:"tin",m:"Tin",h:"the word 'tin'"},{t:"nhắn",m:"Nahn",h:"'nan' like bread"}]},
  "post office": {t:"bưu điện", s:[{t:"bưu",m:"Boo",h:"the word 'boo'"},{t:"điện",m:"Dyen",h:"letter 'D' + 'yen'"}]},
  "stamp": {t:"tem", s:[{t:"tem",m:"Tem",h:"the word 'them' without h"}]},
  "address": {t:"địa chỉ", s:[{t:"địa",m:"Dee-uh",h:"letter 'D' + 'uh'"},{t:"chỉ",m:"Chee",h:"'chi' like Greek letter"}]},
  "phone number": {t:"số điện thoại", s:[{t:"số",m:"Saw",h:"like 'saw' the tool"},{t:"điện",m:"Dyen",h:"letter 'D' + 'yen'"},{t:"thoại",m:"Thwai",h:"'th' + 'way'"}]},
  "what is your number": {t:"số điện thoại bạn là bao nhiêu", s:[{t:"số",m:"Saw",h:"like 'saw' the tool"},{t:"điện",m:"Dyen",h:"letter 'D' + 'yen'"},{t:"thoại",m:"Thwai",h:"'th' + 'way'"},{t:"bạn",m:"Ban",h:"the word 'ban'"},{t:"là",m:"Lah",h:"'la' like a musical note"},{t:"bao",m:"Bow",h:"like 'bow' and arrow"},{t:"nhiêu",m:"Noo",h:"'noon' without last N"}]},
  "take a photo": {t:"chụp ảnh", s:[{t:"chụp",m:"Choop",h:"'chew' + 'p'"},{t:"ảnh",m:"Anh",h:"like the name 'Ann'"}]},
  "computer": {t:"máy tính", s:[{t:"máy",m:"May",h:"the month 'May'"},{t:"tính",m:"Ting",h:"the word 'ting'"}]},

  // ===== HEALTH (10) =====
  "headache": {t:"đau đầu", s:[{t:"đau",m:"Dow",h:"like 'dow' of dow jones"},{t:"đầu",m:"Duh",h:"'duh' like duh sound"}]},
  "stomach ache": {t:"đau bụng", s:[{t:"đau",m:"Dow",h:"like 'dow' of dow jones"},{t:"bụng",m:"Bung",h:"'bung' like cork"}]},
  "fever": {t:"sốt", s:[{t:"sốt",m:"Sawt",h:"'saw' + 't'"}]},
  "medicine": {t:"thuốc", s:[{t:"thuốc",m:"Thook",h:"'took' with th"}]},
  "antibiotic": {t:"thuốc kháng sinh", s:[{t:"thuốc",m:"Thook",h:"'took' with th"},{t:"kháng",m:"Kahng",h:"'kahng' like a word"},{t:"sinh",m:"Sin",h:"the word 'sin'"}]},
  "pain": {t:"đau", s:[{t:"đau",m:"Dow",h:"like 'dow' of dow jones"}]},
  "tired": {t:"mệt", s:[{t:"mệt",m:"Met",h:"the word 'met'"}]},
  "dizzy": {t:"chóng mặt", s:[{t:"chóng",m:"Chong",h:"like 'chong' from Cheech and Chong"},{t:"mặt",m:"Maht",h:"'mat' with ah"}]},
  "nausea": {t:"buồn nôn", s:[{t:"buồn",m:"Bwun",h:"'bwun' like a word"},{t:"nôn",m:"Nawn",h:"'non' + 'n' sound"}]},
  "pharmacy": {t:"nhà thuốc", s:[{t:"nhà",m:"Nyah",h:"'N' then 'yah'"},{t:"thuốc",m:"Thook",h:"'took' with th"}]},

  // ===== TIME (10) =====
  "morning": {t:"buổi sáng", s:[{t:"buổi",m:"Boy",h:"like 'buoy'"},{t:"sáng",m:"Sang",h:"the word 'sang'"}]},
  "afternoon": {t:"buổi chiều", s:[{t:"buổi",m:"Boy",h:"like 'buoy'"},{t:"chiều",m:"Chew",h:"the word 'chew'"}]},
  "evening": {t:"buổi tối", s:[{t:"buổi",m:"Boy",h:"like 'buoy'"},{t:"tối",m:"Toy",h:"the word 'toy'"}]},
  "night": {t:"đêm", s:[{t:"đêm",m:"Dem",h:"like 'them' without h"}]},
  "day": {t:"ngày", s:[{t:"ngày",m:"Ngay",h:"NG sound + 'ay'"}]},
  "week": {t:"tuần", s:[{t:"tuần",m:"Twan",h:"'T' + 'wan'"}]},
  "month": {t:"tháng", s:[{t:"tháng",m:"Tahng",h:"'tong' with ah"}]},
  "year": {t:"năm", s:[{t:"năm",m:"Num",h:"'nom' like nom nom"}]},
  "hour": {t:"giờ", s:[{t:"giờ",m:"Yuh",h:"'yuh' like a word"}]},
  "minute": {t:"phút", s:[{t:"phút",m:"Foot",h:"the word 'foot'"}]},

  // ===== WEATHER & MISC (10) =====
  "hot": {t:"nóng", s:[{t:"nóng",m:"Nong",h:"'n' + 'ong' like song"}]},
  "cold": {t:"lạnh", s:[{t:"lạnh",m:"Lahn",h:"'lahn' like 'land' without d"}]},
  "rain": {t:"mưa", s:[{t:"mưa",m:"Moo-uh",h:"'moo' + 'uh'"}]},
  "sunny": {t:"nắng", s:[{t:"nắng",m:"Nahng",h:"'nong' with ah + ng"}]},
  "cloudy": {t:"có mây", s:[{t:"có",m:"Kaw",h:"like 'caw' of a crow"},{t:"mây",m:"May",h:"the month 'May'"}]},
  "wind": {t:"gió", s:[{t:"gió",m:"Yaw",h:"'yaw' like yawn without n"}]},
  "snow": {t:"tuyết", s:[{t:"tuyết",m:"Twyet",h:"'T' + 'wet'"}]},
  "beautiful": {t:"đẹp", s:[{t:"đẹp",m:"Dep",h:"'dep' like word"}]},
  "ugly": {t:"xấu", s:[{t:"xấu",m:"Saw",h:"like 'saw' the tool"}]},
  "happy": {t:"vui", s:[{t:"vui",m:"Voo",h:"'voo' like in voodoo"}]}
};
