// dict-zh.js — Chinese Mandarin phrase dictionary (200+ entries)
// Auto-generated for HowDoISay app
var DICT_ZH = {
  // === 1. GREETINGS & COURTESY (20) ===
  "hello": {t:"你好", p:"nǐ hǎo", s:[{t:"nǐ",m:"Knee",h:"the word 'knee'"},{t:"hǎo",m:"How",h:"the word 'how'"}]},
  "good morning": {t:"早上好", p:"zǎo shang hǎo", s:[{t:"zǎo",m:"Zow",h:"like 'ow!' with Z"},{t:"shang",m:"Shung",h:"like 'shun'"},{t:"hǎo",m:"How",h:"the word 'how'"}]},
  "good afternoon": {t:"下午好", p:"xià wǔ hǎo", s:[{t:"xià",m:"Shiah",h:"'she' + 'ah'"},{t:"wǔ",m:"Woo",h:"like 'woo!'"},{t:"hǎo",m:"How",h:"the word 'how'"}]},
  "good evening": {t:"晚上好", p:"wǎn shang hǎo", s:[{t:"wǎn",m:"Wahn",h:"'want' without T"},{t:"shang",m:"Shung",h:"like 'shun'"},{t:"hǎo",m:"How",h:"the word 'how'"}]},
  "good night": {t:"晚安", p:"wǎn ān", s:[{t:"wǎn",m:"Wahn",h:"'want' without T"},{t:"ān",m:"Ahn",h:"like 'on'"}]},
  "thank you": {t:"谢谢", p:"xiè xie", s:[{t:"xiè",m:"Sheh",h:"'shed' without D"},{t:"xie",m:"Sheh",h:"'shed' without D"}]},
  "thank you very much": {t:"非常感谢", p:"fēi cháng gǎn xiè", s:[{t:"fēi",m:"Fay",h:"like 'day' with F"},{t:"cháng",m:"Chahng",h:"like 'Chang' (name)"},{t:"gǎn",m:"Gahn",h:"like 'gone'"},{t:"xiè",m:"Sheh",h:"'shed' without D"}]},
  "you're welcome": {t:"不客气", p:"bú kè qì", s:[{t:"bú",m:"Boo",h:"like 'boo!'"},{t:"kè",m:"Kuh",h:"'cup' without the P"},{t:"qì",m:"Chee",h:"like 'cheese' without S"}]},
  "please": {t:"请", p:"qǐng", s:[{t:"qǐng",m:"Ching",h:"like 'cha-ching'"}]},
  "sorry": {t:"对不起", p:"duì bu qǐ", s:[{t:"duì",m:"Dway",h:"'draw' with W"},{t:"bu",m:"Boo",h:"like 'boo!'"},{t:"qǐ",m:"Chee",h:"like 'cheese' without S"}]},
  "excuse me": {t:"打扰一下", p:"dǎ rǎo yī xià", s:[{t:"dǎ",m:"Dah",h:"the word 'duh'"},{t:"rǎo",m:"Rao",h:"the word 'row'"},{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"xià",m:"Shiah",h:"'she' + 'ah'"}]},
  "goodbye": {t:"再见", p:"zài jiàn", s:[{t:"zài",m:"Zigh",h:"like 'sigh' with Z"},{t:"jiàn",m:"Jee-en",h:"'gee' then 'N'"}]},
  "see you later": {t:"回见", p:"huí jiàn", s:[{t:"huí",m:"Hoo-ay",h:"'who' + 'ay'"},{t:"jiàn",m:"Jee-en",h:"'gee' then 'N'"}]},
  "how are you": {t:"你好吗", p:"nǐ hǎo ma", s:[{t:"nǐ",m:"Knee",h:"the word 'knee'"},{t:"hǎo",m:"How",h:"the word 'how'"},{t:"ma",m:"Mah",h:"like 'ma'"}]},
  "i'm fine": {t:"我很好", p:"wǒ hěn hǎo", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"hěn",m:"Hun",h:"the word 'hun'"},{t:"hǎo",m:"How",h:"the word 'how'"}]},
  "nice to meet you": {t:"很高兴认识你", p:"hěn gāo xìng rèn shi nǐ", s:[{t:"hěn",m:"Hun",h:"the word 'hun'"},{t:"gāo",m:"Gow",h:"like 'cow'"},{t:"xìng",m:"Shing",h:"'shin' + G"},{t:"rèn",m:"Ren",h:"like 'run' without U"},{t:"shi",m:"Sure",h:"like 'sure' but shorter"},{t:"nǐ",m:"Knee",h:"the word 'knee'"}]},
  "my name is": {t:"我叫", p:"wǒ jiào", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"jiào",m:"Joe",h:"the name 'Joe'"}]},
  "what is your name": {t:"你叫什么名字", p:"nǐ jiào shén me míng zi", s:[{t:"nǐ",m:"Knee",h:"the word 'knee'"},{t:"jiào",m:"Joe",h:"the name 'Joe'"},{t:"shén",m:"Shun",h:"like 'shun'"},{t:"me",m:"Muh",h:"like 'muh'"},{t:"míng",m:"Ming",h:"like 'Ming' dynasty"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "pleased to meet you": {t:"很荣幸", p:"hěn róng xìng", s:[{t:"hěn",m:"Hun",h:"the word 'hun'"},{t:"róng",m:"Rong",h:"like 'wrong' with R"},{t:"xìng",m:"Shing",h:"'shin' + G"}]},

  // === 2. YES/NO/BASICS (10) ===
  "yes": {t:"是", p:"shì", s:[{t:"shì",m:"Sure",h:"like 'sure' but shorter"}]},
  "no": {t:"不", p:"bù", s:[{t:"bù",m:"Boo",h:"like 'boo!'"}]},
  "okay": {t:"好的", p:"hǎo de", s:[{t:"hǎo",m:"How",h:"the word 'how'"},{t:"de",m:"Duh",h:"the word 'duh'"}]},
  "i understand": {t:"我明白", p:"wǒ míng bai", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"míng",m:"Ming",h:"like 'Ming' dynasty"},{t:"bai",m:"By",h:"the word 'bye'"}]},
  "i don't understand": {t:"我不明白", p:"wǒ bù míng bai", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"bù",m:"Boo",h:"like 'boo!'"},{t:"míng",m:"Ming",h:"like 'Ming' dynasty"},{t:"bai",m:"By",h:"the word 'bye'"}]},
  "do you speak english": {t:"你说英文吗", p:"nǐ shuō yīng wén ma", s:[{t:"nǐ",m:"Knee",h:"the word 'knee'"},{t:"shuō",m:"Shwuh",h:"like 'shun' but shorter"},{t:"yīng",m:"Ying",h:"like 'ying'"},{t:"wén",m:"Wen",h:"like 'when'"},{t:"ma",m:"Mah",h:"like 'ma'"}]},
  "slowly please": {t:"请慢一点", p:"qǐng màn yī diǎn", s:[{t:"qǐng",m:"Ching",h:"like 'cha-ching'"},{t:"màn",m:"Mahn",h:"like 'moan'"},{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"diǎn",m:"Dyen",h:"'ten' with Y"}]},
  "repeat please": {t:"再说一遍", p:"zài shuō yī biàn", s:[{t:"zài",m:"Zigh",h:"like 'sigh' with Z"},{t:"shuō",m:"Shwuh",h:"like 'shun' but shorter"},{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"biàn",m:"Byun",h:"'bee' + 'un'"}]},
  "wait a moment": {t:"等一下", p:"děng yī xià", s:[{t:"děng",m:"Dung",h:"the word 'dung'"},{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"xià",m:"Shiah",h:"'she' + 'ah'"}]},

  // === 3. EMERGENCY & SAFETY (15) ===
  "help": {t:"救命", p:"jiù mìng", s:[{t:"jiù",m:"Joe",h:"the name 'Joe'"},{t:"mìng",m:"Ming",h:"like 'Ming' dynasty"}]},
  "emergency": {t:"紧急", p:"jǐn jí", s:[{t:"jǐn",m:"Jin",h:"like 'chin'"},{t:"jí",m:"Jee",h:"like 'gee'"}]},
  "hospital": {t:"医院", p:"yī yuàn", s:[{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"yuàn",m:"Yoo-en",h:"'you' + 'N'"}]},
  "police": {t:"警察", p:"jǐng chá", s:[{t:"jǐng",m:"Jing",h:"like 'ching' with J"},{t:"chá",m:"Chah",h:"like 'cha'"}]},
  "fire": {t:"火", p:"huǒ", s:[{t:"huǒ",m:"Hwuh",h:"like 'huh' with W"}]},
  "danger": {t:"危险", p:"wēi xiǎn", s:[{t:"wēi",m:"Way",h:"the word 'way'"},{t:"xiǎn",m:"Shyen",h:"'shee' + 'en'"}]},
  "poison": {t:"毒", p:"dú", s:[{t:"dú",m:"Doo",h:"like 'do'"}]},
  "thief": {t:"小偷", p:"xiǎo tōu", s:[{t:"xiǎo",m:"Sh-ow",h:"'shower' without '-er'"},{t:"tōu",m:"Toe",h:"the word 'toe'"}]},
  "accident": {t:"事故", p:"shì gù", s:[{t:"shì",m:"Sure",h:"like 'sure' but shorter"},{t:"gù",m:"Goo",h:"the word 'goo'"}]},
  "sick": {t:"病", p:"bìng", s:[{t:"bìng",m:"Bing",h:"like 'Bing' search"}]},
  "hurt": {t:"疼", p:"téng", s:[{t:"téng",m:"Tung",h:"like 'tung'"}]},
  "call doctor": {t:"叫医生", p:"jiào yī shēng", s:[{t:"jiào",m:"Joe",h:"the name 'Joe'"},{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"shēng",m:"Shung",h:"like 'shun' + G"}]},
  "medicine": {t:"药", p:"yào", s:[{t:"yào",m:"Yow",h:"like 'yow!'"}]},
  "bathroom": {t:"厕所", p:"cè suǒ", s:[{t:"cè",m:"Tsuh",h:"like 'cats' (ts sound)"},{t:"suǒ",m:"Swaw",h:"'saw' with S in front"}]},
  "water (drinking)": {t:"饮用水", p:"yǐn yòng shuǐ", s:[{t:"yǐn",m:"Yin",h:"like 'yin' and yang"},{t:"yòng",m:"Yong",h:"'young' without the U"},{t:"shuǐ",m:"Shway",h:"like 'sway' with SH"}]},

  // === 4. NUMBERS 0-10, 20, 50, 100, 1000 (15) ===
  "zero": {t:"零", p:"líng", s:[{t:"líng",m:"Ling",h:"like 'ling'"}]},
  "one": {t:"一", p:"yī", s:[{t:"yī",m:"Ee",h:"the letter 'E'"}]},
  "two": {t:"二", p:"èr", s:[{t:"èr",m:"Are",h:"the word 'are'"}]},
  "three": {t:"三", p:"sān", s:[{t:"sān",m:"San",h:"like 'San' Francisco"}]},
  "four": {t:"四", p:"sì", s:[{t:"sì",m:"Sir",h:"the word 'sir'"}]},
  "five": {t:"五", p:"wǔ", s:[{t:"wǔ",m:"Woo",h:"like 'woo!'"}]},
  "six": {t:"六", p:"liù", s:[{t:"liù",m:"Lyoo",h:"like 'loo' with L"}]},
  "seven": {t:"七", p:"qī", s:[{t:"qī",m:"Chee",h:"like 'cheese' without S"}]},
  "eight": {t:"八", p:"bā", s:[{t:"bā",m:"Bah",h:"like 'bah'"}]},
  "nine": {t:"九", p:"jiǔ", s:[{t:"jiǔ",m:"Joe",h:"the name 'Joe'"}]},
  "ten": {t:"十", p:"shí", s:[{t:"shí",m:"Sure",h:"like 'sure' but shorter"}]},
  "twenty": {t:"二十", p:"èr shí", s:[{t:"èr",m:"Are",h:"the word 'are'"},{t:"shí",m:"Sure",h:"like 'sure' but shorter"}]},
  "fifty": {t:"五十", p:"wǔ shí", s:[{t:"wǔ",m:"Woo",h:"like 'woo!'"},{t:"shí",m:"Sure",h:"like 'sure' but shorter"}]},
  "one hundred": {t:"一百", p:"yī bǎi", s:[{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"bǎi",m:"By",h:"the word 'bye'"}]},
  "one thousand": {t:"一千", p:"yī qiān", s:[{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"qiān",m:"Chee-en",h:"'cheese' without S, then 'N'"}]},

  // === 5. FOOD & DRINK (30) ===
  "water": {t:"水", p:"shuǐ", s:[{t:"shuǐ",m:"Shway",h:"like 'sway' with SH"}]},
  "tea": {t:"茶", p:"chá", s:[{t:"chá",m:"Chah",h:"like 'cha'"}]},
  "coffee": {t:"咖啡", p:"kā fēi", s:[{t:"kā",m:"Ka",h:"like 'ka-boom'"},{t:"fēi",m:"Fay",h:"like 'day' with F"}]},
  "beer": {t:"啤酒", p:"pí jiǔ", s:[{t:"pí",m:"Pee",h:"the letter 'P'"},{t:"jiǔ",m:"Joe",h:"the name 'Joe'"}]},
  "wine": {t:"酒", p:"jiǔ", s:[{t:"jiǔ",m:"Joe",h:"the name 'Joe'"}]},
  "milk": {t:"奶", p:"nǎi", s:[{t:"nǎi",m:"Nye",h:"like Bill 'Nye'"}]},
  "juice": {t:"果汁", p:"guǒ zhī", s:[{t:"guǒ",m:"Gwah",h:"like 'gwa-' in 'guava'"},{t:"zhī",m:"Juh",h:"like 'judge' but shorter"}]},
  "rice": {t:"米饭", p:"mǐ fàn", s:[{t:"mǐ",m:"Mee",h:"the word 'me'"},{t:"fàn",m:"Fan",h:"the word 'fan'"}]},
  "noodles": {t:"面条", p:"miàn tiáo", s:[{t:"miàn",m:"Myen",h:"'me' + 'N'"},{t:"tiáo",m:"Tyao",h:"'tea' + 'ow'"}]},
  "bread": {t:"面包", p:"miàn bāo", s:[{t:"miàn",m:"Myen",h:"'me' + 'N'"},{t:"bāo",m:"Bow",h:"the word 'bow'"}]},
  "egg": {t:"蛋", p:"dàn", s:[{t:"dàn",m:"Don",h:"the name 'Don'"}]},
  "chicken": {t:"鸡", p:"jī", s:[{t:"jī",m:"Jee",h:"like 'gee'"}]},
  "pork": {t:"猪肉", p:"zhū ròu", s:[{t:"zhū",m:"Joo",h:"like 'judge' but shorter"},{t:"ròu",m:"Row",h:"the word 'row'"}]},
  "beef": {t:"牛肉", p:"niú ròu", s:[{t:"niú",m:"Nyo",h:"like 'new'"},{t:"ròu",m:"Row",h:"the word 'row'"}]},
  "fish": {t:"鱼", p:"yú", s:[{t:"yú",m:"Yoo",h:"like 'you'"}]},
  "vegetable": {t:"蔬菜", p:"shū cài", s:[{t:"shū",m:"Shoo",h:"like 'shoo!'"},{t:"cài",m:"Ts-eye",h:"'cats' without CA, then 'eye'"}]},
  "fruit": {t:"水果", p:"shuǐ guǒ", s:[{t:"shuǐ",m:"Shway",h:"like 'sway' with SH"},{t:"guǒ",m:"Gwah",h:"like 'gwa-' in 'guava'"}]},
  "apple": {t:"苹果", p:"píng guǒ", s:[{t:"píng",m:"Ping",h:"like 'ping' pong"},{t:"guǒ",m:"Gwah",h:"like 'gwa-' in 'guava'"}]},
  "banana": {t:"香蕉", p:"xiāng jiāo", s:[{t:"xiāng",m:"Shyahng",h:"'she' + 'ahng'"},{t:"jiāo",m:"Joe",h:"the name 'Joe'"}]},
  "rice bowl": {t:"碗饭", p:"wǎn fàn", s:[{t:"wǎn",m:"Wahn",h:"'want' without T"},{t:"fàn",m:"Fan",h:"the word 'fan'"}]},
  "spoon": {t:"勺子", p:"sháo zi", s:[{t:"sháo",m:"Sh-ow",h:"'shower' without '-er'"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "chopsticks": {t:"筷子", p:"kuài zi", s:[{t:"kuài",m:"Kwai",h:"like 'quai'"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "plate": {t:"盘子", p:"pán zi", s:[{t:"pán",m:"Pan",h:"the word 'pan'"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "fork": {t:"叉子", p:"chā zi", s:[{t:"chā",m:"Chah",h:"like 'cha'"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "knife": {t:"刀", p:"dāo", s:[{t:"dāo",m:"Dow",h:"like 'dow'"}]},
  "hot": {t:"热", p:"rè", s:[{t:"rè",m:"Ruh",h:"'rung' without the NG"}]},
  "cold": {t:"冷", p:"lěng", s:[{t:"lěng",m:"Lung",h:"the word 'lung'"}]},
  "sweet": {t:"甜", p:"tián", s:[{t:"tián",m:"Tyen",h:"'ten' with Y"}]},
  "salty": {t:"咸", p:"xián", s:[{t:"xián",m:"Shyen",h:"'shee' + 'en'"}]},
  "sour": {t:"酸", p:"suān", s:[{t:"suān",m:"Swan",h:"the word 'swan'"}]},
  "spicy": {t:"辣", p:"là", s:[{t:"là",m:"Lah",h:"like 'la' in do-re-mi"}]},

  // === 6. RESTAURANT (15) ===
  "restaurant": {t:"餐厅", p:"cān tīng", s:[{t:"cān",m:"Tsan",h:"'T' + 'San'"},{t:"tīng",m:"Ting",h:"a 'ting' sound"}]},
  "table": {t:"桌子", p:"zhuō zi", s:[{t:"zhuō",m:"Jwuh",h:"like 'judge' but shorter"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "menu": {t:"菜单", p:"cài dān", s:[{t:"cài",m:"Ts-eye",h:"'cats' without CA, then 'eye'"},{t:"dān",m:"Dahn",h:"like 'dahn'"}]},
  "waiter": {t:"服务员", p:"fú wù yuán", s:[{t:"fú",m:"Foo",h:"like 'foo!'"},{t:"wù",m:"Woo",h:"like 'woo!'"},{t:"yuán",m:"Yoo-en",h:"'you' + 'N'"}]},
  "bill": {t:"账单", p:"zhàng dān", s:[{t:"zhàng",m:"Jahng",h:"'judge' + 'ahng'"},{t:"dān",m:"Dahn",h:"like 'dahn'"}]},
  "check please": {t:"买单", p:"mǎi dān", s:[{t:"mǎi",m:"My",h:"the word 'my'"},{t:"dān",m:"Dahn",h:"like 'dahn'"}]},
  "i would like": {t:"我想要", p:"wǒ xiǎng yào", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"xiǎng",m:"Shyahng",h:"'she' + 'ahng'"},{t:"yào",m:"Yow",h:"like 'yow!'"}]},
  "i'll have": {t:"我要", p:"wǒ yào", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"yào",m:"Yow",h:"like 'yow!'"}]},
  "can you recommend": {t:"你能推荐吗", p:"nǐ néng tuī jiàn ma", s:[{t:"nǐ",m:"Knee",h:"the word 'knee'"},{t:"néng",m:"Nung",h:"'tongue' without the TO"},{t:"tuī",m:"Tway",h:"'way' with T in front"},{t:"jiàn",m:"Jee-en",h:"'gee' then 'N'"},{t:"ma",m:"Mah",h:"like 'ma'"}]},
  "no sugar": {t:"不要糖", p:"bú yào táng", s:[{t:"bú",m:"Boo",h:"like 'boo!'"},{t:"yào",m:"Yow",h:"like 'yow!'"},{t:"táng",m:"Tong",h:"the word 'tong'"}]},
  "no salt": {t:"不要盐", p:"bú yào yán", s:[{t:"bú",m:"Boo",h:"like 'boo!'"},{t:"yào",m:"Yow",h:"like 'yow!'"},{t:"yán",m:"Yen",h:"like Japanese 'yen'"}]},
  "no spicy": {t:"不要辣", p:"bú yào là", s:[{t:"bú",m:"Boo",h:"like 'boo!'"},{t:"yào",m:"Yow",h:"like 'yow!'"},{t:"là",m:"Lah",h:"like 'la' in do-re-mi"}]},
  "more": {t:"更多", p:"gèng duō", s:[{t:"gèng",m:"Gung",h:"like 'gung'"},{t:"duō",m:"Dwaw",h:"'draw' with W"}]},
  "less": {t:"少一点", p:"shǎo yī diǎn", s:[{t:"shǎo",m:"Sh-ow",h:"'shower' without '-er'"},{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"diǎn",m:"Dyen",h:"'ten' with Y"}]},
  "delicious": {t:"好吃", p:"hǎo chī", s:[{t:"hǎo",m:"How",h:"the word 'how'"},{t:"chī",m:"Chir",h:"like 'cheer' shorter"}]},

  // === 7. SHOPPING & MONEY (20) ===
  "shop": {t:"店", p:"diàn", s:[{t:"diàn",m:"Dyen",h:"'ten' with Y"}]},
  "market": {t:"市场", p:"shì chǎng", s:[{t:"shì",m:"Sure",h:"like 'sure' but shorter"},{t:"chǎng",m:"Chahng",h:"like 'Chang' (name)"}]},
  "price": {t:"价格", p:"jià gé", s:[{t:"jià",m:"Jiah",h:"'gee' + 'ah'"},{t:"gé",m:"Guh",h:"'gut' without the T"}]},
  "how much": {t:"多少钱", p:"duō shǎo qián", s:[{t:"duō",m:"Dwaw",h:"'draw' with W"},{t:"shǎo",m:"Sh-ow",h:"'shower' without '-er'"},{t:"qián",m:"Chee-en",h:"'cheese' without S, then 'N'"}]},
  "money": {t:"钱", p:"qián", s:[{t:"qián",m:"Chee-en",h:"'cheese' without S, then 'N'"}]},
  "expensive": {t:"贵", p:"guì", s:[{t:"guì",m:"Gway",h:"'way' with G in front"}]},
  "cheap": {t:"便宜", p:"pián yi", s:[{t:"pián",m:"Pyen",h:"'pee' + 'N'"},{t:"yi",m:"Ee",h:"the letter 'E'"}]},
  "i'll buy it": {t:"我买", p:"wǒ mǎi", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"mǎi",m:"My",h:"the word 'my'"}]},
  "discount": {t:"折扣", p:"zhé kòu", s:[{t:"zhé",m:"Juh",h:"like 'judge' but shorter"},{t:"kòu",m:"Co",h:"like 'co-' in coworker"}]},
  "receipt": {t:"收据", p:"shōu jù", s:[{t:"shōu",m:"Show",h:"the word 'show'"},{t:"jù",m:"Joo",h:"like 'judge' but shorter"}]},
  "credit card": {t:"信用卡", p:"xìn yòng kǎ", s:[{t:"xìn",m:"Shin",h:"the word 'shin'"},{t:"yòng",m:"Yong",h:"'young' without the U"},{t:"kǎ",m:"Kah",h:"like 'kah'"}]},
  "cash": {t:"现金", p:"xiàn jīn", s:[{t:"xiàn",m:"Shyen",h:"'shee' + 'en'"},{t:"jīn",m:"Jin",h:"like 'chin'"}]},
  "change": {t:"找零", p:"zhǎo líng", s:[{t:"zhǎo",m:"Joe",h:"the name 'Joe'"},{t:"líng",m:"Ling",h:"like 'ling'"}]},
  "size": {t:"大小", p:"dà xiǎo", s:[{t:"dà",m:"Dah",h:"the word 'duh'"},{t:"xiǎo",m:"Sh-ow",h:"'shower' without '-er'"}]},
  "color": {t:"颜色", p:"yán sè", s:[{t:"yán",m:"Yen",h:"like Japanese 'yen'"},{t:"sè",m:"Suh",h:"like 'suh'"}]},
  "red": {t:"红", p:"hóng", s:[{t:"hóng",m:"Hong",h:"like 'Hong' Kong"}]},
  "blue": {t:"蓝", p:"lán", s:[{t:"lán",m:"Lahn",h:"like 'lahn'"}]},
  "white": {t:"白", p:"bái", s:[{t:"bái",m:"By",h:"the word 'bye'"}]},
  "black": {t:"黑", p:"hēi", s:[{t:"hēi",m:"Hay",h:"the word 'hay'"}]},

  // === 8. DIRECTIONS & TRANSPORTATION (25) ===
  "taxi": {t:"出租车", p:"chū zū chē", s:[{t:"chū",m:"Choo",h:"like 'choo!'"},{t:"zū",m:"Zoo",h:"the word 'zoo'"},{t:"chē",m:"Chuh",h:"'chug' without the G"}]},
  "bus": {t:"公共汽车", p:"gōng gòng qì chē", s:[{t:"gōng",m:"Gong",h:"the word 'gong'"},{t:"gòng",m:"Gong",h:"the word 'gong'"},{t:"qì",m:"Chee",h:"like 'cheese' without S"},{t:"chē",m:"Chuh",h:"'chug' without the G"}]},
  "train": {t:"火车", p:"huǒ chē", s:[{t:"huǒ",m:"Hwuh",h:"like 'huh' with W"},{t:"chē",m:"Chuh",h:"'chug' without the G"}]},
  "airplane": {t:"飞机", p:"fēi jī", s:[{t:"fēi",m:"Fay",h:"like 'day' with F"},{t:"jī",m:"Jee",h:"like 'gee'"}]},
  "car": {t:"车", p:"chē", s:[{t:"chē",m:"Chuh",h:"'chug' without the G"}]},
  "bike": {t:"自行车", p:"zì xíng chē", s:[{t:"zì",m:"Zuh",h:"like 'zu'"},{t:"xíng",m:"Shing",h:"like 'shing'"},{t:"chē",m:"Chuh",h:"'chug' without the G"}]},
  "metro/subway": {t:"地铁", p:"dì tiě", s:[{t:"dì",m:"Dee",h:"the letter 'D'"},{t:"tiě",m:"Tyeh",h:"'tea' + 'eh'"}]},
  "station": {t:"站", p:"zhàn", s:[{t:"zhàn",m:"Jahn",h:"like 'john' without O"}]},
  "airport": {t:"机场", p:"jī chǎng", s:[{t:"jī",m:"Jee",h:"like 'gee'"},{t:"chǎng",m:"Chahng",h:"like 'Chang' (name)"}]},
  "street": {t:"街", p:"jiē", s:[{t:"jiē",m:"Jyeh",h:"'gee' + 'eh'"}]},
  "road": {t:"路", p:"lù", s:[{t:"lù",m:"Loo",h:"the word 'loo'"}]},
  "bridge": {t:"桥", p:"qiáo", s:[{t:"qiáo",m:"Chyao",h:"'cheese' + 'ow'"}]},
  "turn left": {t:"左转", p:"zuǒ zhuǎn", s:[{t:"zuǒ",m:"Zwuh",h:"like 'swa' with Z"},{t:"zhuǎn",m:"Jwahn",h:"'judge' + 'ahn'"}]},
  "turn right": {t:"右转", p:"yòu zhuǎn", s:[{t:"yòu",m:"Yo",h:"like 'yo!'"},{t:"zhuǎn",m:"Jwahn",h:"'judge' + 'ahn'"}]},
  "go straight": {t:"直走", p:"zhí zǒu", s:[{t:"zhí",m:"Jir",h:"like 'judge' but shorter"},{t:"zǒu",m:"Zoe",h:"like 'zoe'"}]},
  "near": {t:"近", p:"jìn", s:[{t:"jìn",m:"Jin",h:"like 'chin'"}]},
  "far": {t:"远", p:"yuǎn", s:[{t:"yuǎn",m:"Yoo-en",h:"'you' + 'N'"}]},
  "north": {t:"北", p:"běi", s:[{t:"běi",m:"Bay",h:"the word 'bay'"}]},
  "south": {t:"南", p:"nán", s:[{t:"nán",m:"Nahn",h:"like 'nahn'"}]},
  "east": {t:"东", p:"dōng", s:[{t:"dōng",m:"Dong",h:"like 'ding dong'"}]},
  "west": {t:"西", p:"xī", s:[{t:"xī",m:"She",h:"the word 'she'"}]},
  "here": {t:"这里", p:"zhè li", s:[{t:"zhè",m:"Juh",h:"like 'judge' but shorter"},{t:"li",m:"Lee",h:"the name 'Lee'"}]},
  "there": {t:"那里", p:"nà li", s:[{t:"nà",m:"Nah",h:"the word 'nah'"},{t:"li",m:"Lee",h:"the name 'Lee'"}]},
  "how do i get to": {t:"我怎样去", p:"wǒ zěn yàng qù", s:[{t:"wǒ",m:"Waw",h:"'wall' without LL"},{t:"zěn",m:"Zen",h:"the word 'zen'"},{t:"yàng",m:"Yahng",h:"like 'yahng'"},{t:"qù",m:"Choo",h:"like 'choo choo' train"}]},

  // === 9. ACCOMMODATION (15) ===
  "hotel": {t:"酒店", p:"jiǔ diàn", s:[{t:"jiǔ",m:"Joe",h:"the name 'Joe'"},{t:"diàn",m:"Dyen",h:"'ten' with Y"}]},
  "room": {t:"房间", p:"fáng jiān", s:[{t:"fáng",m:"Fong",h:"like 'fong' in ping-pong"},{t:"jiān",m:"Jyen",h:"'gee' + 'en'"}]},
  "reservation": {t:"预约", p:"yù yuē", s:[{t:"yù",m:"Yoo",h:"like 'you'"},{t:"yuē",m:"Yoo-eh",h:"'you' + 'eh'"}]},
  "check in": {t:"办理入住", p:"bàn lǐ rù zhù", s:[{t:"bàn",m:"Bon",h:"like 'bon' voyage"},{t:"lǐ",m:"Lee",h:"the name 'Lee'"},{t:"rù",m:"Roo",h:"like 'rue'"},{t:"zhù",m:"Joo",h:"like 'judge' but shorter"}]},
  "check out": {t:"结账", p:"jié zhàng", s:[{t:"jié",m:"Jyeh",h:"'gee' + 'eh'"},{t:"zhàng",m:"Jahng",h:"'judge' + 'ahng'"}]},
  "key": {t:"钥匙", p:"yào shi", s:[{t:"yào",m:"Yow",h:"like 'yow!'"},{t:"shi",m:"Sure",h:"like 'sure' but shorter"}]},
  "lock": {t:"锁", p:"suǒ", s:[{t:"suǒ",m:"Swaw",h:"'saw' with S in front"}]},
  "bed": {t:"床", p:"chuáng", s:[{t:"chuáng",m:"Chwahng",h:"'chew' + 'ahng'"}]},
  "bathroom": {t:"浴室", p:"yù shì", s:[{t:"yù",m:"Yoo",h:"like 'you'"},{t:"shì",m:"Sure",h:"like 'sure' but shorter"}]},
  "shower": {t:"淋浴", p:"lín yù", s:[{t:"lín",m:"Lin",h:"the name 'Lin'"},{t:"yù",m:"Yoo",h:"like 'you'"}]},
  "towel": {t:"毛巾", p:"máo jīn", s:[{t:"máo",m:"Mao",h:"like 'Mao' (rhymes with cow)"},{t:"jīn",m:"Jin",h:"like 'chin'"}]},
  "blanket": {t:"毯子", p:"tǎn zi", s:[{t:"tǎn",m:"Tahn",h:"like 'tahn'"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "pillow": {t:"枕头", p:"zhěn tou", s:[{t:"zhěn",m:"Jun",h:"short for 'June'"},{t:"tou",m:"Toe",h:"the word 'toe'"}]},
  "wifi": {t:"网络", p:"wǎng luò", s:[{t:"wǎng",m:"Wahng",h:"like 'wahng'"},{t:"luò",m:"Lwaw",h:"'L' then 'wall' without LL"}]},
  "quiet": {t:"安静", p:"ān jìng", s:[{t:"ān",m:"Ahn",h:"like 'on'"},{t:"jìng",m:"Jing",h:"like 'ching' with J"}]},

  // === 10. COMMUNICATION (15) ===
  "phone": {t:"电话", p:"diàn huà", s:[{t:"diàn",m:"Dyen",h:"'ten' with Y"},{t:"huà",m:"Hwah",h:"'hwa-' like 'what' without T"}]},
  "mobile phone": {t:"手机", p:"shǒu jī", s:[{t:"shǒu",m:"Show",h:"the word 'show'"},{t:"jī",m:"Jee",h:"like 'gee'"}]},
  "call": {t:"打电话", p:"dǎ diàn huà", s:[{t:"dǎ",m:"Dah",h:"the word 'duh'"},{t:"diàn",m:"Dyen",h:"'ten' with Y"},{t:"huà",m:"Hwah",h:"'hwa-' like 'what' without T"}]},
  "text message": {t:"短信", p:"duǎn xìn", s:[{t:"duǎn",m:"Dwahn",h:"'dwan' + short"},{t:"xìn",m:"Shin",h:"the word 'shin'"}]},
  "email": {t:"电子邮件", p:"diàn zi yóu jiàn", s:[{t:"diàn",m:"Dyen",h:"'ten' with Y"},{t:"zi",m:"Zuh",h:"like 'zu'"},{t:"yóu",m:"Yoe",h:"like 'yoe'"},{t:"jiàn",m:"Jee-en",h:"'gee' then 'N'"}]},
  "internet": {t:"互联网", p:"hù lián wǎng", s:[{t:"hù",m:"Hoo",h:"like 'hoo!'"},{t:"lián",m:"Lyen",h:"'lee' + 'en'"},{t:"wǎng",m:"Wahng",h:"like 'wahng'"}]},
  "translate": {t:"翻译", p:"fān yì", s:[{t:"fān",m:"Fahn",h:"like 'fahn'"},{t:"yì",m:"Ee",h:"the letter 'E'"}]},
  "address": {t:"地址", p:"dì zhǐ", s:[{t:"dì",m:"Dee",h:"the letter 'D'"},{t:"zhǐ",m:"Jir",h:"like 'judge' but shorter"}]},
  "phone number": {t:"电话号码", p:"diàn huà hào mǎ", s:[{t:"diàn",m:"Dyen",h:"'ten' with Y"},{t:"huà",m:"Hwah",h:"'hwa-' like 'what' without T"},{t:"hào",m:"How",h:"the word 'how'"},{t:"mǎ",m:"Mah",h:"like 'mah'-jongg"}]},
  "name": {t:"名字", p:"míng zi", s:[{t:"míng",m:"Ming",h:"like 'Ming' dynasty"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "surname": {t:"姓", p:"xìng", s:[{t:"xìng",m:"Shing",h:"'shin' + G"}]},
  "last name": {t:"姓氏", p:"xìng shì", s:[{t:"xìng",m:"Shing",h:"'shin' + G"},{t:"shì",m:"Sure",h:"like 'sure' but shorter"}]},
  "first name": {t:"名字", p:"míng zi", s:[{t:"míng",m:"Ming",h:"like 'Ming' dynasty"},{t:"zi",m:"Zuh",h:"like 'zu'"}]},
  "social media": {t:"社交媒体", p:"shè jiāo méi tǐ", s:[{t:"shè",m:"Shuh",h:"'shut' without the T"},{t:"jiāo",m:"Joe",h:"the name 'Joe'"},{t:"méi",m:"May",h:"the word 'may'"},{t:"tǐ",m:"Tee",h:"the letter 'T'"}]},
  "wechat": {t:"微信", p:"wēi xìn", s:[{t:"wēi",m:"Way",h:"the word 'way'"},{t:"xìn",m:"Shin",h:"the word 'shin'"}]},

  // === 11. HEALTH (10) ===
  "doctor": {t:"医生", p:"yī shēng", s:[{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"shēng",m:"Shung",h:"like 'shun' + G"}]},
  "hospital": {t:"医院", p:"yī yuàn", s:[{t:"yī",m:"Ee",h:"the letter 'E'"},{t:"yuàn",m:"Yoo-en",h:"'you' + 'N'"}]},
  "medicine": {t:"药", p:"yào", s:[{t:"yào",m:"Yow",h:"like 'yow!'"}]},
  "pharmacy": {t:"药店", p:"yào diàn", s:[{t:"yào",m:"Yow",h:"like 'yow!'"},{t:"diàn",m:"Dyen",h:"'ten' with Y"}]},
  "fever": {t:"发烧", p:"fā shāo", s:[{t:"fā",m:"Fah",h:"like 'fa' in do-re-mi"},{t:"shāo",m:"Sh-ow",h:"'shower' without '-er'"}]},
  "cough": {t:"咳嗽", p:"ké sou", s:[{t:"ké",m:"Kuh",h:"like 'kuh'"},{t:"sou",m:"Sue",h:"the word 'sue'"}]},
  "headache": {t:"头疼", p:"tóu téng", s:[{t:"tóu",m:"Toe",h:"the word 'toe'"},{t:"téng",m:"Tung",h:"like 'tung'"}]},
  "allergy": {t:"过敏", p:"guò mǐn", s:[{t:"guò",m:"Gwah",h:"like 'gwa-' in 'guava'"},{t:"mǐn",m:"Min",h:"short for 'minute'"}]},
  "pain": {t:"疼痛", p:"téng tòng", s:[{t:"téng",m:"Tung",h:"like 'tung'"},{t:"tòng",m:"Tong",h:"like 'tong'"}]},
  "sleep": {t:"睡觉", p:"shuì jiào", s:[{t:"shuì",m:"Shway",h:"like 'sway' with SH"},{t:"jiào",m:"Joe",h:"the name 'Joe'"}]},

  // === 12. TIME (10) ===
  "today": {t:"今天", p:"jīn tiān", s:[{t:"jīn",m:"Jin",h:"like 'chin'"},{t:"tiān",m:"Tyen",h:"'ten' with Y"}]},
  "yesterday": {t:"昨天", p:"zuó tiān", s:[{t:"zuó",m:"Zwuh",h:"like 'swa' with Z"},{t:"tiān",m:"Tyen",h:"'ten' with Y"}]},
  "tomorrow": {t:"明天", p:"míng tiān", s:[{t:"míng",m:"Ming",h:"like 'Ming' dynasty"},{t:"tiān",m:"Tyen",h:"'ten' with Y"}]},
  "morning": {t:"早上", p:"zǎo shang", s:[{t:"zǎo",m:"Zow",h:"like 'ow!' with Z"},{t:"shang",m:"Shung",h:"like 'shun'"}]},
  "afternoon": {t:"下午", p:"xià wǔ", s:[{t:"xià",m:"Shiah",h:"'she' + 'ah'"},{t:"wǔ",m:"Woo",h:"like 'woo!'"}]},
  "evening": {t:"晚上", p:"wǎn shang", s:[{t:"wǎn",m:"Wahn",h:"'want' without T"},{t:"shang",m:"Shung",h:"like 'shun'"}]},
  "night": {t:"夜晚", p:"yè wǎn", s:[{t:"yè",m:"Yeh",h:"the word 'yeah'"},{t:"wǎn",m:"Wahn",h:"'want' without T"}]},
  "hour": {t:"小时", p:"xiǎo shí", s:[{t:"xiǎo",m:"Sh-ow",h:"'shower' without '-er'"},{t:"shí",m:"Sure",h:"like 'sure' but shorter"}]},
  "minute": {t:"分钟", p:"fēn zhōng", s:[{t:"fēn",m:"Fen",h:"the word 'fen'"},{t:"zhōng",m:"Jung",h:"like 'judge' + 'ng'"}]},
  "second": {t:"秒", p:"miǎo", s:[{t:"miǎo",m:"Miao",h:"'me' + 'ow'"}]},

  // === 13. WEATHER & MISC (10) ===
  "sunny": {t:"晴朗", p:"qíng lǎng", s:[{t:"qíng",m:"Ching",h:"like 'cha-ching'"},{t:"lǎng",m:"Lahng",h:"like 'lahng'"}]},
  "rainy": {t:"下雨", p:"xià yǔ", s:[{t:"xià",m:"Shiah",h:"'she' + 'ah'"},{t:"yǔ",m:"Yoo",h:"like 'you'"}]},
  "snow": {t:"雪", p:"xuě", s:[{t:"xuě",m:"Shway",h:"like 'sway' with SH"}]},
  "wind": {t:"风", p:"fēng", s:[{t:"fēng",m:"Fung",h:"'fun' + G"}]},
  "cloud": {t:"云", p:"yún", s:[{t:"yún",m:"Yoon",h:"'moon' with Y"}]},
  "cold (weather)": {t:"冷", p:"lěng", s:[{t:"lěng",m:"Lung",h:"the word 'lung'"}]},
  "hot (weather)": {t:"热", p:"rè", s:[{t:"rè",m:"Ruh",h:"'rung' without the NG"}]},
  "warm": {t:"温暖", p:"wēn nuǎn", s:[{t:"wēn",m:"Wen",h:"like 'when'"},{t:"nuǎn",m:"Noo-en",h:"'noo' + 'N'"}]},
  "cool": {t:"凉爽", p:"liáng shuǎng", s:[{t:"liáng",m:"Lyang",h:"'lee' + 'ang'"},{t:"shuǎng",m:"Shwahng",h:"'shuh' + 'ahng'"}]},
  "beautiful": {t:"美丽", p:"měi lì", s:[{t:"měi",m:"May",h:"the word 'may'"},{t:"lì",m:"Lee",h:"the name 'Lee'"}]}
};
